Ladder Refactor
cs-23-sw-6-12/plc-learner pull request #22
Opened 2023-04-26 10:45 UTC by KiraStaehr

2023-04-26 11:38 UTC, t-lohse requested changes

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +                if (eqVals.getSecond().toString().contains("true")) {
Tænker en anden måde at finde `true` vil være bedre end at lave det om til en string. Er der ikke en `any`, `contains` el.lign.

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +    }
Jeg ved ik hvor smart det er at have en class til både åben og lukket, burde det ikke bare være et `private boolean open` i `Gate` som kan sættes i constructoren?

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Visualization/SVGNCC.java
> +    public SVGNCC(double x, double y, String text) {
Det samme som over, hvorfor have en class til hver når man bare kunne tjekke dens felt og act accordingly? De gør jo det samme, bare closed skal have en ekstra streg

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/commands/ExportSvgCommand.java
> +}
?

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Visualization/SVGCoil.java
> +package org.cs23sw612.Ladder.Visualization;
Ka vi ik have et subdir til SVG visualization?

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
>                  if ((long) equation.getFullList().size() > 1 && !first)
Why typecast?

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
>                  if ((long) equation.getFullList().size() > 1 && !first)
Og ka du ik bare bruge `.length()`?

2023-04-26 11:38 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +        public ArrayList<Rung> ORRungs = new ArrayList<>();
Ku denne class evt. overloade `add(Rung rung)` som så adder til or-rungs? På den måde ku vi undgå at sku ha det `first` tjek over osv. Og on `OrRung` har stadig outputs i sig, så tror ik at det er en nødvendig class(?)

Og naming er forkert

2023-04-26 11:52 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +                if (eqVals.getSecond().toString().contains("true")) {
evt. bare undlad det her tjek

2023-04-26 11:59 UTC, KiraStaehr commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +                if (eqVals.getSecond().toString().contains("true")) {
Altså vi  kan stream den, hvis det er bedre?  getSecond i sig selv har minus brugbart (som jeg kan se)🤷‍♀️

2023-04-26 12:06 UTC, KiraStaehr commented on src/main/java/org/cs23sw612/commands/ExportSvgCommand.java
> +}
Just remove

2023-04-26 12:07 UTC, KiraStaehr commented on src/main/java/org/cs23sw612/Ladder/Visualization/SVGCoil.java
> +package org.cs23sw612.Ladder.Visualization;
sure

2023-05-03 12:17 UTC, JE-FH requested changes
very nice

2023-05-03 12:17 UTC, JE-FH commented on src/main/java/org/cs23sw612/Ladder/Ladder.java
> +        private <IO extends Word<Boolean>> Rung(Triple<Word<Boolean>, Word<Boolean>, IO> eqVals) {
Tag 3 forskellige argumenter istedet for en triple

2023-05-03 12:17 UTC, JE-FH commented on src/main/java/org/cs23sw612/Ladder/Visualization/Visualizer.java
> +        /*
Fjern kommentar kode

2023-05-03 12:17 UTC, JE-FH commented on src/main/java/org/cs23sw612/commands/VisualizeCommand.java
> +    Pair<@Nullable Word<Boolean>, @Nullable Word<Boolean>> ParseBool(Map<String, String> attr) {
Bedre navngivning pls

2023-05-08 07:38 UTC, Laursen79 requested changes
Does Ladder support Word<Integer> like the rest of plc-learner uses?

2023-05-08 07:38 UTC, Laursen79 commented on src/main/java/org/cs23sw612/commands/VisualizeCommand.java
> +    Pair<@Nullable Word<Boolean>, @Nullable Word<Boolean>> ParseIntegerWords(Map<String, String> attr) {
ParseIntegerWords parses Boolean Words?

2023-05-08 07:57 UTC, Laursen79 approved these changes

2023-05-08 07:59 UTC, t-lohse approved these changes

2023-05-08 08:19 UTC, JE-FH approved these changes
Yes det er nice

2023-05-09 06:44 UTC, merged