New visualizer
cs-23-sw-6-12/plc-learner pull request #33
Opened 2023-08-01 12:08 UTC by KiraStaehr

Visualizer ladder generated from bed

2023-08-29 17:05 UTC, t-lohse requested changes

2023-08-29 17:05 UTC, t-lohse commented on src/main/java/org/cs23sw612/Ladder/Visualization/SVG/NewSVGCoil.java
> +        path.lineTo(x + 25, y);
Kunne disse hardcoded værdier ikke være nogle `const`s?

2023-09-03 10:31 UTC, KiraStaehr commented on src/main/java/org/cs23sw612/Ladder/Visualization/SVG/NewSVGCoil.java
> +        path.lineTo(x + 25, y);
Jo, jeg gad bare ik fikse det, lol. Men det burde det være. Ville nemlig også have ændret i dem, men fordi de var hardcoded skippede jeg det 🙃 😁

2023-09-09 08:41 UTC, JE-FH commented
Det ser godt ud. Den eneste forbedring jeg kunne forstille mig ville være hvis det var skrevet i Haskell.

2023-10-17 06:09 UTC, t-lohse approved these changes

2023-10-17 06:09 UTC, merged